name: Check PR Status
on:
 push:
 pull_request:
 workflow_dispatch:
jobs:
  check-pr-status:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check PR status
        id: pr_status
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
              echo "draft" > pr-status.txt
          else
              echo "not-draft" > pr-status.txt
          fi
      - name: Upload PR status
        uses: actions/upload-artifact@v4
        with:
          name: pr-status
          path: pr-status.txt
          