name: Check PR Status
on:
 push:
 pull_request:
 workflow_dispatch:
jobs:
  check-pr-status:
    if: github.event_name == 'pull_request' || github.event.pull_request.event == 'ready_for_review'
    runs-on: ubuntu-latest
    steps:
      - name: Check PR status
        id: pr_status
        run: |
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
              echo "draft" > pr-status.txt
          else
              echo "not-draft" > pr-status.txt
          fi
      - name: Upload PR status
        uses: actions/upload-artifact@v4
        with:
          name: pr-status
          path: pr-status.txt
  trigger-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 10
      - name: Trigger e2e-dev workflow
        run: |
            echo "This job is needed to impersonate the jenkins workflow_dispatch event."
            curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/TanyaKars/workflows/workflows/e2e.yaml/dispatches \
            -d '{"ref":"${{ github.ref }}"}'