name: E2E TEST 1
on:
  workflow_call:
env:
jobs:
  call-check-enviroment:
    name: Use local generate-config
    uses: ./.github/workflows/generate-config.yaml
  smoke:
    name: SMOKE
    needs: call-check-enviroment
    runs-on: ubuntu-latest
    container: cypress/browsers:node-20.13.1-chrome-125.0.6422.60-1-ff-126.0-edge-125.0.2535.51-1
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: create env file
        run: |
          touch .env
          echo URL_PREFIX=${{ inputs.featureUrl }} >> .env
      - name: Cypress run
        uses: cypress-io/github-action@v6.7.0

        with:
          browser: chrome
          working-directory: ./e2e
          spec: cypress/e2e/_smoke.cy.ts
          config-file: cypress.dev-${{ needs.call-check-enviroment.outputs.ref_type }}.config.ts
          env: configFile=dev
      - name: Store screenshot artifacts
        uses: actions/upload-artifact@v4.3.4
        if: failure()
        with:
          name: e2e-screenshots
          path: ./e2e/cypress/results
  suit-1:
    name: Suit-1
    needs: call-check-enviroment
    runs-on: ubuntu-latest
    container: cypress/browsers:node-20.13.1-chrome-125.0.6422.60-1-ff-126.0-edge-125.0.2535.51-1
    strategy:
      fail-fast: false
      matrix:
        containers: [folder-1, folder-2, folder-3]
    defaults:
      run:
        working-directory: e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: create env file
        run: |
          touch .env
          echo URL_PREFIX=${{ inputs.featureUrl }} >> .env
      - name: Cypress run
        uses: cypress-io/github-action@v6.7.0
        with:
          browser: chrome
          working-directory: ./e2e
          spec: cypress/e2e/suit-1/${{ matrix.containers }}.cy.ts
          config-file: cypress.dev-${{ needs.call-check-enviroment.outputs.ref_type }}.config.ts
          env: configFile=dev
      - name: Store screenshot artifacts
        uses: actions/upload-artifact@v4.3.4
        if: failure()
        with:
          name: e2e-screenshots-${{ matrix.containers }}
          path: ./e2e/cypress/results
