name: e2e
on:
    workflow_dispatch:
jobs:
    on-draft:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4 
        - name: Download PR status
          uses: dawidd6/action-download-artifact@v3
          with:
            workflow: check-pr-status.yaml
            name: pr-status
        - name: Read PR status
          id: read
          run: |
            if [ ! -f pr-status.txt ]; then
              echo "pr_status.txt not found"
              exit 1
            fi
            PR_STATUS=$(cat pr-status.txt)
            echo "PR_STATUS=$PR_STATUS" >> $GITHUB_ENV
        - name: Make status success if PR is draft
          if: ${{ env.PR_STATUS == 'draft' }}
          continue-on-error: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO: ${{ github.repository }}
            RUN_ID: ${{ github.run_id }}
          run: |
            echo "PR is draft"
            echo "Cancelling the workflow run"
            gh api \
              --method POST \
              -H "Accept: application/vnd.github.v3+json" \
              /repos/$REPO/actions/runs/$RUN_ID/cancel
    e2e:
        runs-on: ubuntu-latest
        steps:
        - name: Print
          run: |
            echo "This is working!"
            